#!/bin/bash

# Reset firewalld rules and set default zones to drop
firewall-cmd --complete-reload
firewall-cmd --set-default-zone=drop

# Allow loopback communication
firewall-cmd --add-interface=lo --permanent

# Allow HTTP (port 80) and HTTPS (port 443) outbound
firewall-cmd --add-port=80/tcp --permanent
firewall-cmd --add-port=443/tcp --permanent

# Allow DNS (UDP) outbound
# firewall-cmd --add-port=53/udp --permanent

# Allow NTP (UDP) outbound and inbound
# firewall-cmd --add-port=123/udp --permanent

# Allow incoming ICMP (ping) requests
firewall-cmd --add-icmp-block=echo-request --permanent

# Allow MariaDB/MySQL traffic
# firewall-cmd --add-port=3306/tcp --permanent

# uncomment script lines below and edit source address for specific servers
# Allow DNS (UDP) outbound from specific source IP addresses (add this once DNS is configured)
# firewall-cmd --add-rich-rule='rule family="ipv4" source address="your_internal_dns_server_ip" port protocol="udp" port="53" accept' --permanent

# Allow NTP (UDP) outbound and inbound from specific source IP addresses (add this once NTP is configured)
# firewall-cmd --add-rich-rule='rule family="ipv4" source address="your_internal_ntp_server_ip" port protocol="udp" port="123" accept' --permanent


# Reload firewalld to apply the rules
firewall-cmd --reload
